version: '3'

services:
    db:
        build:
            context: ./docker/db
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
        ports:
            - "33006:3306"
        volumes:
            - ./docker/db/data:/var/lib/mysql

    php-fpm:
        build:
            context: ./docker/php-fpm
        depends_on:
            - db
        environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
            - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:3306/${DATABASE_NAME}
        volumes:
            - ./:/var/www

    nginx:
        build:
            context: ./docker/nginx
        volumes:
            - ./:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites/:/etc/nginx/sites-available
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./docker/logs:/var/log
        depends_on:
            - php-fpm
        ports:
            - "8000:80"